### ISSUE TITLE
Parking Lot Epic

### ISSUE THREAD

**Issue by alfredodan** [Project-Overworld/.github#2]
### Description

Features that will be assigned later on.

### Definition of Done

- [ ] All features are done
- [ ] All code is tested in the dev-* branch.
- [ ] All new defects related to this feature have been resolved.
- [ ] Documentation for the epic is created.
